Repository 18F/identity-pki, pull requests merged in 2020-04, with the labels that each got.

#127 LG-2605 Add new state.gov certs
  config/certs/C=US, O=U.S. Government, OU=Department of State, OU=PIV, OU=Certification Authorities, OU=U.S. Department of State PIV CA2 20200323.pem
  config/certs/C=US, O=U.S. Government, OU=FPKI, CN=Federal Common Policy CA 20200323.pem
  config/certs/DC=sbu, DC=state, CN=Configuration, CN=Services, CN=Public Key Services, CN=AIA, CN=U.S. Department of State AD Root CA 20200323.pem
Labels: status - do not merge, status - ready for review

#137 Add tests for invalid and duplicate certs in the repo
  config/certs/C=US, O=Entrust, OU=Certification Authorities, OU=Entrust Managed Services SSP CA 01.pem
  config/certs/C=US, O=U.S. Government, OU=Department of Energy, OU=Certification Authorities, CN=DOE SSP CA 01.pem
  config/certs/C=US, O=U.S. Government, OU=Department of State, OU=PIV, OU=Certification Authorities, OU=U.S. Department of State PIV CA2.pem
  config/certs/C=US, O=U.S. Government, OU=Department of the Treasury, OU=Fiscal Service 01.pem
  config/certs/C=US, O=U.S. Government, OU=Department of the Treasury, OU=Fiscal Service 02.pem
  config/certs/C=US, O=U.S. Government, OU=DoD, OU=PKI, CN=DOD CA-31.pem
  config/certs/C=US, O=U.S. Government, OU=DoD, OU=PKI, CN=DOD CA-32.pem
  config/certs/C=US, O=U.S. Government, OU=DoD, OU=PKI, CN=DOD EMAIL CA-31.pem
  config/certs/C=US, O=U.S. Government, OU=DoD, OU=PKI, CN=DOD EMAIL CA-32.pem
  config/certs/C=US, O=U.S. Government, OU=DoD, OU=PKI, CN=DoD Interoperability Root CA 1.pem
  config/certs/C=US, O=U.S. Government, OU=FPKI, CN=SHA-1 Federal Root CA G2.pem
  config/certs/C=US, O=U.S. Government, OU=HHS, OU=Certification Authorities, CN=HHS-FPKI-Intermediate-CA-E1 01.pem
  config/certs/C=US, O=U.S. Government, OU=NASA, OU=Certification Authorities, OU=NASA Operational CA.pem
  config/certs/C=US, O=U.S. Government, OU=U.S. Department of Education, CN=U.S. Department of Education Device CA - G3.pem
  config/certs/C=US, O=U.S. Government, OU=U.S. Department of Energy, CN=Naval Reactors SSP Device CA G2.pem
  config/certs/C=US, O=U.S. Government, OU=U.S. Department of Transportation, CN=U.S. Department of Transportation SSP Device CA G3.pem
  config/certs/C=US, O=U.S. Government, OU=U.S. Nuclear Regulatory Commission, CN=NRC SSP Device CA G2.pem
  config/certs/DC=sbu, DC=state, CN=Configuration, CN=Services, CN=Public Key Services, CN=AIA, CN=U.S. Department of State AD High Assurance CA 01.pem
  config/certs/DC=sbu, DC=state, CN=Configuration, CN=Services, CN=Public Key Services, CN=AIA, CN=U.S. Department of State AD High Assurance CA 02.pem
  config/certs/DC=sbu, DC=state, CN=Configuration, CN=Services, CN=Public Key Services, CN=AIA, CN=U.S. Department of State AD Root CA 02.pem
  config/certs/DC=sbu, DC=state, CN=Configuration, CN=Services, CN=Public Key Services, CN=AIA, CN=U.S. Department of State AD Root CA.pem
  config/certs/DC=sbu, DC=state, CN=Configuration, CN=Services, CN=Public Key Services, CN=AIA, CN=U.S. Department of State PIV CA.pem
  lib/tasks/certs.rake
  spec/certs/store_spec.rb
  spec/rails_helper.rb
Labels: status - ready for review

#131 LG-2605 Add new state.gov certs
  config/certs/C=US, O=U.S. Government, OU=Department of State, OU=PIV, OU=Certification Authorities, OU=U.S. Department of State PIV CA2.pem
  config/certs/DC=sbu, DC=state, CN=Configuration, CN=Services, CN=Public Key Services, CN=AIA, CN=U.S. Department of State AD Root CA.pem
  spec/certs/store_spec.rb
Labels: status - do not merge
